### ISSUE TITLE
[PE-D][Tester D] Able to change the sale price evem though there is no sale price

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113T-T09-2/tp#219] opened 2024-04-06 03:17 UTC
![Screenshot 2024-04-05 172622.png](https://raw.githubusercontent.com/nyh3/ped/main/files/220158ba-1e8c-4bac-af8e-3c93dcfc3949.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nyh3/ped#8

**Comment by nkotaa** [comment] 2024-04-07 11:59
Duplicate of #208

**Closed by nkotaa** 2024-04-07 11:59 UTC
