### ISSUE TITLE
[PE-D][Tester B] Threshold value not showing for op item

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113T-T09-2/tp#224] opened 2024-04-06 03:30 UTC
![image.png](https://raw.githubusercontent.com/Xb990219/ped/main/files/752cd7ed-302f-4f33-8b47-3464679ec844.png)

Is this intended? 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: Xb990219/ped#5

**Comment by nkotaa** [comment] 2024-04-07 12:03
Duplicate of #191

**Closed by nkotaa** 2024-04-07 12:03 UTC
